### ISSUE TITLE
Responsive menu

### ISSUE THREAD

**Issue by andreimarin90** [andreimarin90/C3#12]
![screen shot 2015-11-06 at 14 19 30](https://cloud.githubusercontent.com/assets/8208159/10996910/7f9cc59e-8491-11e5-8df5-1b1cf477e481.jpg)
![screen shot 2015-11-06 at 14 19 37](https://cloud.githubusercontent.com/assets/8208159/10996911/7fc88ada-8491-11e5-9fc4-2ba1b801fba5.jpg)
intre 2 breaks nu e deloc menu sau hamburger. Unde apare ham nu merge.

**Comment by arlad** [comment]
Fixed
