### ISSUE TITLE
Ad Space centrat

### ISSUE THREAD

**Issue by andreimarin90** [andreimarin90/C3#2]
![screen shot 2015-10-09 at 13 45 55](https://cloud.githubusercontent.com/assets/8208159/10392026/1698c0a4-6e8c-11e5-8a1a-c6d77abb7ad1.jpg)

**Comment by andreimarin90** [comment]
La fel si pe fullwidth si bagat si margin bottom.

**Comment by andreimarin90** [comment]
http://bigbangthemes.net/C3_WP/2015/08/30/this-is-just-getting-better-and-better/ top, bottom.

**Comment by andreimarin90** [comment]
![c3_post ads_sidebar](https://cloud.githubusercontent.com/assets/8208159/10972262/1c832f08-83e1-11e5-9c3c-f0284dcd04cb.jpg)

**Comment by andreimarin90** [comment]
poti schimba markup daca ai nevoie, in special pentru cele din single page de mai jos. In root/single.php gasesti.

**Comment by arlad** [comment]
Fixed
