### ISSUE TITLE
Ad space strica nth-child(2n) la article

### ISSUE THREAD

**Issue by andreimarin90** [andreimarin90/C3#3]
![screen shot 2015-10-09 at 13 46 21](https://cloud.githubusercontent.com/assets/8208159/10392032/25a1686c-6e8c-11e5-859a-e308edcceb9c.jpg)
Nu stiu de ce strica. vezi ca e posibil sa existe sau nu ad space, deci trebuie gasita solutie universala.

**Comment by andreimarin90** [comment]
poti schimba markup la ad sa pui altceva in loc de div, si sa faci cu :first-of-type instead of -nth-child.

**Comment by arlad** [comment]
Fixed
