### ISSUE TITLE
Lipsa Slider no space up top

### ISSUE THREAD

**Issue by andreimarin90** [andreimarin90/C3#4]
![screen shot 2015-10-09 at 13 48 13](https://cloud.githubusercontent.com/assets/8208159/10392067/6ad6b6ee-6e8c-11e5-8b07-4df6baa78249.jpg)
Daca lipseste sliderul nu mai are margins pagina, la fel si sidebarul. tre invers, pagina si sidebar sa aiba spatii top si sliderul sa nu aiba bottom.

**Comment by arlad** [comment]
Fixed
