### ISSUE TITLE
Widget issues

### ISSUE THREAD

**Issue by andreimarin90** [andreimarin90/C3#9]
![screen shot 2015-11-06 at 13 58 14](https://cloud.githubusercontent.com/assets/8208159/10996529/813d2af4-848e-11e5-971c-f2fb67d21cc1.jpg)
![screen shot 2015-11-06 at 13 58 34](https://cloud.githubusercontent.com/assets/8208159/10996528/813a3056-848e-11e5-9094-b030c331d354.jpg)

Dungile nu sunt ca in HTML. Am gresit eu markup?

**Comment by arlad** [comment]
Fixed
